### ISSUE TITLE
cannot install via pip?

### ISSUE THREAD

**Issue by prankousky** [julzhk/usb_barcode_scanner#1]
Hi,

I just tried installing this on a raspberry pi via `pip install usb-barcode-scanner` as well as `pip3 install usb-barcode-scanner` (with and without prepended `sudo` command). This is the error I get

```
testkram ➤ sudo pip3 install usb-barcode-scanner
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting usb-barcode-scanner
  Could not find a version that satisfies the requirement usb-barcode-scanner (from versions: )
No matching distribution found for usb-barcode-scanner
```

I am having trouble with my barcode reader script, so I was hoping I could use this library instead, but for some reason, it will not work.

Is there an alternative way to install? Thank you for your support :)

**Comment by MichaelMichaelMichaelMichaelMichael** [comment]
I'm having the same issue, I've tried upgrading pip and setuptools, unfortunately that didn't solve the issue. I'm using Raspbian, the newest version from May 27th 2020.

**Comment by julzhk** [comment]
Hi thank you for getting in touch! I'm delighted your attempting to use it. I hope we can get it working for you! 

Pip installing: I'll look into it but as a work around while I fix it, you can ignore pip & download the code (it's just one file) into your project. So just download this: [https://github.com/julzhk/usb_barcode_scanner/blob/master/scanner.py ](https://github.com/julzhk/usb_barcode_scanner/blob/master/scanner.py )

Then you can import and use it as documented. Let me know how you get on!

**Comment by prankousky** [comment]
Thank you @julzhk 

I realized that this was an option and did that already :) But since this was supposed to be installable via pip, I didn't close the issue. It works as intended. 

However! I am running this on a raspberry pi in combination with a script that will publish any read code via mqtt (`paho-mqtt`). I want to run this script via cron upon startup, but currently run it manually via command line to test it. When I start the script, it will work. The barcode will be printed in the command line as well as published as an mqtt payload.

If I scan 25 codes or so, it will not publish any codes. Previously, I'd then stop the script and run it again, which will result in it working again. However, then I just kept it running. The script will work after a few minutes or so again (so first it works, then it stops working, then it suddenly works again, and so on). It will stop again and start again, and I cannot determine why this is. Are you using this 24/7 and know how to fix that?

This happens with both a wired USB barcode scanner as well as one that is wirelessly connected via dongle. The wireless barcode reader **will** even work when you turn it off and on again (so this is not a connectivity timeout), but eventually stop, then start working again just like the USB one did.

My goal is to read barcodes that I can then pass on to Home Assistant, which will do different things (for example, consume/add items from/to `grocy`, but also things unrelated to grocy, so I cannot just use `barcodebuddy`, which should take care of grocy-only things).

**Comment by julzhk** [comment]
hi Yep: If you didn't submit it, I'd not know it was broken in pip.

You mention some interesting technologies! MQTT is very interesting to me, so thanks for that intro.
re grocy: Yes, I heard of this in hacker news a while back: tracking groceries was the reason I was playing with barcode scanners in the first place. I should revisit it & polish it for release. 

The scanner writes the character code to the buffer at : /dev/hidraw0
[https://github.com/julzhk/usb_barcode_scanner/blob/master/scanner.py#L25](https://github.com/julzhk/usb_barcode_scanner/blob/master/scanner.py#L25)

I suggest trying 
``` 
tail -f /dev/hidraw0
```

Hopefully this verifies the scanner is scanning! There is some delay inherent in a queue system: maybe by the time MQTT reads the data, the buffer has changed or cleared somehow. Hope this helps..

**Comment by prankousky** [comment]
Thank you. It's weird. I can always tail the device, but the code will not always be submitted via mqtt (or shown in the command line). MQTT will always submit the data right when it is read (within the same loop), so there shouldn't be a timeout. Also, the code will not be shown in the command line either, which it should even if there were problems with the mqtt part, correct?

**Comment by wisehackermonkey** [comment]
im having the same issue!

any progress on fixing the pip issue?

![](https://i.postimg.cc/XqYjn5ct/image.png)

Python version
```
Python 3.8.3
```
os windows 10

**Comment by julzhk** [comment]
Hi : Been a bit busy. Thanks for all your kind reports , but I will try to get to it this week. Apologies for the delay.

**Comment by julzhk** [comment]
Hi Updated the version so it should be available in pip install now. Note: slight pip package name change.
