### ISSUE TITLE
Barcode scanner not handheld. 

### ISSUE THREAD

**Issue by Ramzi04** [julzhk/usb_barcode_scanner#10]
Is it possible to use this library to read from a barcode scanner that is not handhold.

**Comment by hansegucker** [comment]
This should work with any scanner that emulates an USB keyboard – most scanners do this by default.

**Comment by Esaleddin** [comment]
Dies sollte mit jedem Scanner funktionieren, der eine USB-Tastatur emuliert – die meisten Scanner tun dies standardmäßig.

Vielen Dank für die richtige Antwort

**Comment by julzhk** [comment]
thanks @hansegucker for your help
