### ISSUE TITLE
Read Timeout

### ISSUE THREAD

**Issue by keoozDan** [julzhk/usb_barcode_scanner#12]
How could we do a timeout for the read ?
I want that the script stop automatically after 60 seconds.

**Comment by julzhk** [comment]
I'll just add some pseudo-code, which should give you some hints:
where the code has the 'forever loop' - ie `while true:` you'll want to stop after a period of time.

so at the start of the script set a variable for the `start_time`
And change the while statement to:
`while current_time < start_time + 60_seconds:`

This should have the desired effect. I'll leave it to you to look up how to look up the elapsed time, current time and finish this off.

Best of luck with your project!
