### ISSUE TITLE
How to control bar code scanner beep with data validation?

### ISSUE THREAD

**Issue by samshipengs** [julzhk/usb_barcode_scanner#15]
Do you know if there is a way to only let the scanner beep after validating the scanned data? For example I posted a question on SO: https://stackoverflow.com/questions/75536330/how-to-control-bar-code-scanner-beep-with-data-validation

Thanks!

**Comment by julzhk** [comment]
If it's possible then it'll be in the documentation with your particular scanner. I really don't think there's a general way to achieve this. Sorry!
