### ISSUE TITLE
ModuleNotFoundError: No module named 'scanner'

### ISSUE THREAD

**Issue by 007fred50** [julzhk/usb_barcode_scanner#3]
Hello,

i try to use your USB barcode scanner.

```
import logging

from scanner import barcode_reader

# simple usage  - in python 3
if __name__ == '__main__':
    try:
        while True:
            upcnumber = barcode_reader()
            print(upcnumber)
    except KeyboardInterrupt:
        logging.debug('Keyboard interrupt')
    except Exception as err:
        logging.error(err)
```

But i get this error here something i did wrong?
```
Traceback (most recent call last):
  File "scan.py", line 3, in <module>
    from scanner import barcode_reader
ModuleNotFoundError: No module named 'scanner'
```

python --version
Python 3.7.2

python -m pip --version
pip 20.3.3 from C:\Users\fredy\AppData\Local\Programs\Python\Python37\lib\site-packages\pip (python 3.7)

thanks for your time :)

**Comment by zadnas4nt** [comment]
your forget the install code
pip install usb-barcode-scanner

or
in your script this line
from usb_scanner.scanner import barcode_reader

**Comment by julzhk** [comment]
duplicate
