### ISSUE TITLE
ModuleNotFoundError: No module named 'usb_scanner'

### ISSUE THREAD

**Issue by 007fred50** [julzhk/usb_barcode_scanner#4]
Hello,

i have isntalled your plugin (https://pypi.org/project/usb-barcode-scanner/)

but then i run the code:
```
from usb_scanner.scanner import barcode_reader
if __name__ == '__main__':
    try:
        while True:
            upcnumber = barcode_reader()
            print(upcnumber)
    except KeyboardInterrupt:
        logging.debug('Keyboard interrupt')
    except Exception as err:
        logging.error(err)
```
it say ModuleNotFoundError: No module named 'usb_scanner'

can you help me out?

**Comment by julzhk** [comment]
Hi Fred:
Sorry for the confusion - can you try installing this pip project instead? It's the one that's updated.

pip install usb-barcode-scanner-julz

I'll update the read me to be a bit clearer.

Best of luck with your scanner!

**Comment by julzhk** [comment]
Thanks for the report - I'll take a look at it ASAP.

**Comment by ryleymcc** [comment]
Try putting scanner.py in the same folder as the sample .py that you are running.

**Comment by zadnas4nt** [comment]
try edit your code in import statement

from "usb_scanner.scanner"
to  "usb-barcode-scanner.scanner"

**Comment by julzhk** [comment]
thanks again @zadnas4nt : best wishes to you!
