### ISSUE TITLE
Support for windows?

### ISSUE THREAD

**Issue by ryleymcc** [julzhk/usb_barcode_scanner#5]
When I run the sample.py on windows I get an error that it can't find the /dev/hidraw0 usb path. This makes sense since it's windows and I don't actually have a scanner but I'd like to make it work. Would you please look into this?

https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/pos-barcodescanner-configure 

I need to use this in an app that isn't in focus so I need to use it with the HID POS Scanner driver.
If you can't make it work I will just use an Arduino with a usb shield or something and then interface with pyserial.

**Comment by julzhk** [comment]
Sorry I've not been able to help - I hope you solved your issue. I personally would indeed use an Arduino or raspberry pi, as that's more familiar.
