### ISSUE TITLE
Read barcodes

### ISSUE THREAD

**Issue by DJboyy1** [julzhk/usb_barcode_scanner#6]
i installed everything and i think it works only got the error "ERROR:root:[Errno 2] No such file or directory: '/dev/hidraw0' " but the barcode scanner is on his way so can't test now but i don't know how i can scan a barcode and that code will be used somewhere any help ?

**Comment by aschurf** [comment]
enter 'ls /dev/' in terminal, check your connection devices. Or run command, check all hidraw, connect scanner to usb and run command again. If you have other devices connected, you may need to use hidraw1, hidraw2, etc.

**Comment by zadnas4nt** [comment]
you're used a windows system or other of linux?

this code work just in linux

**Comment by yoonsik-woo** [comment]
Hi, I want to ask fot the Result data how to convert to excel. Could you load that code?

**Comment by julzhk** [comment]
thank you @zadnas4nt  for your help. I'll highlight the fact it's just for linux in the docs. 

Best of luck with your project @yoonsik-woo.
