### ISSUE TITLE
QR Scanner.

### ISSUE THREAD

**Issue by SpaceDux** [julzhk/usb_barcode_scanner#7]
Hi, I have an issue and unsure where to fix. I've mapped 83 (which == ALT), I've also told it to ignore 83 as it's irrelevant to the scanner, however I still receive the error. The final out-printed scan is perfect, except it's in an error.

I would be a grateful for any help.

```terminal
83
11
23
23
19
22
2
2
51
56
56
21
8
25
19
4
28
55
24
14
56
34
31
30
39
38
35
30
37
40
Scan Request: ?https://revpay.uk/52109618
ERROR:root:Expecting value: line 1 column 1 (char 0)
```
scanner.py
````
#!/usr/bin/python

# Inspired by https://www.piddlerintheroot.com/barcode-scanner/
# https://www.raspberrypi.org/forums/viewtopic.php?f=45&t=55100
# from 'brechmos' - thank-you!

CHARMAP_LOWERCASE = {4: 'a', 5: 'b', 6: 'c', 7: 'd', 8: 'e', 9: 'f', 10: 'g', 11: 'h', 12: 'i', 13: 'j', 14: 'k',
                     15: 'l', 16: 'm', 17: 'n', 18: 'o', 19: 'p', 20: 'q', 21: 'r', 22: 's', 23: 't', 24: 'u', 25: 'v',
                     26: 'w', 27: 'x', 28: 'y', 29: 'z', 30: '1', 31: '2', 32: '3', 33: '4', 34: '5', 35: '6', 36: '7',
                     37: '8', 38: '9', 39: '0', 44: ' ', 45: '-', 46: '=', 47: '[', 48: ']', 49: '\\', 51: ';',
                     52: '\'', 53: '~', 54: ',', 55: '.', 56: '/'}

CHARMAP_UPPERCASE = {4: 'A', 5: 'B', 6: 'C', 7: 'D', 8: 'E', 9: 'F', 10: 'G', 11: 'H', 12: 'I', 13: 'J', 14: 'K',
                     15: 'L', 16: 'M', 17: 'N', 18: 'O', 19: 'P', 20: 'Q', 21: 'R', 22: 'S', 23: 'T', 24: 'U', 25: 'V',
                     26: 'W', 27: 'X', 28: 'Y', 29: 'Z', 30: '!', 31: '@', 32: '#', 33: '$', 34: '%', 35: '^', 36: '&',
                     37: '*', 38: '(', 39: ')', 44: ' ', 45: '_', 46: '+', 47: '{', 48: '}', 49: '|', 51: ':', 52: '"',
                     53: '~', 54: '<', 55: '>', 56: '?'}
CR_CHAR = 40
SHIFT_CHAR = 2
ERROR_CHARACTER = '?'
ALT_KEY = 83


def barcode_reader():
    barcode_string_output = ''
    # barcode can have a 'shift' character; this switches the character set
    # from the lower to upper case variant for the next character only.
    CHARMAP = CHARMAP_LOWERCASE
    with open('/dev/hidraw0', 'rb') as fp:
        while True:
            # step through returned character codes, ignore zeroes
            for char_code in [element for element in fp.read(8) if element > 0 and element < 83]:
                print(char_code)
                if char_code == CR_CHAR:
                    # all barcodes end with a carriage return
                    return barcode_string_output
                if char_code == SHIFT_CHAR:
                    # use uppercase character set next time
                    CHARMAP = CHARMAP_UPPERCASE
                else:
                    # if the charcode isn't recognized, use ?
                    barcode_string_output += CHARMAP.get(char_code, ERROR_CHARACTER)
                    # reset to lowercase character map
                    CHARMAP = CHARMAP_LOWERCASE

```

Thank's in advanced.

**Comment by SpaceDux** [comment]
Ignore this, it's absolutely fine. I'm just an idiot :D

**Comment by parmeshwalunj** [comment]
> Ignore this, it's absolutely fine. I'm just an idiot :D

Loved your honesty level. Did it work well?

**Comment by SpaceDux** [comment]
Absolute perfect once you take my idiocy away. 😂

Works exactly as you'd require.

**Comment by parmeshwalunj** [comment]
As you have done this, I have a question. **Will this work directly with the python code when the barcode scanner device is connected through the PC's USB(as I don't want to use raspberry pi or anything else)?** 

_Giving you an insight into my project-_ I want to make a python project which will simply scan the barcodes(items at the general store or any other shop) and calculate the bill. 

Thanking you in advance for your help!

**Comment by SpaceDux** [comment]
It certainly should. If you're running on Linux and have a usb scanner, it should work as expected, I never tried it on windows 🤔.

From my experience. It works well with EAN-8 barcodes & QR codes, it should work with everything aslong as its a keyboard scanner (hidraw, outputs like a keyboard)

**Comment by SpaceDux** [comment]
My repo "RevController" is the script where I use this package.

It's a shower controller, not a POS, but you can see how I use it.

Hope this helps.

**Comment by parmeshwalunj** [comment]
Thanks @SpaceDux Nice to talk to you. Can we be in contact as I'm working on different projects, surely I'll need your help.

**Comment by SpaceDux** [comment]
Sure, just email me if you have any questions in the future.

ryan.a.williams@outlook.com

**Comment by parmeshwalunj** [comment]
Surely, I will. Thank you!
