### ISSUE TITLE
Package Reading Wrong UPC Value

### ISSUE THREAD

**Issue by redixhumayun** [julzhk/usb_barcode_scanner#8]
I tried out this package and it seems to read the wrong values.

For instance, I have a CODE-128 barcode with the following value: `RtTwtZDJe_`

However, what the package outputs is: `RTTWtZDJE_`

Here are the print statements when trying to debug this

```
2 shift
2 shift
21 R
2 shift
23 RT
2 shift
2 shift
23 RTT
2 shift
26 RTTW
23 RTTWt
2 shift
2 shift
29 RTTWtZ
2 shift
2 shift
7 RTTWtZD
2 shift
2 shift
13 RTTWtZDJ
2 shift
8 RTTWtZDJE
2 shift
2 shift
45 RTTWtZDJE_
2 shift
```

So, it looks like two successive shifts mean that it should switch from one charset to another. If I follow that algorithm, it works correctly.

Can you provide feedback on this?

For reference, I am using a Honeywell MS-5145 barcode scanner plugged in via USB to a Raspberry Pi 4.

**Comment by julzhk** [comment]
Sorry for the late reply - If you managed to solve the problem, let me know and I'll include some notes or amend the code. Appears that the look-up for the shift character isn't recognised - chaining the shift character might work.

Best wishes with your project
