### ISSUE TITLE
grabbing the device

### ISSUE THREAD

**Issue by michalfapso** [julzhk/usb_barcode_scanner#9]
Thanks for this project! I just needed the scanned code to be only processed by the python script and not to arrive in an active window as a normal keyboard input. I modified your code to use the `evdev` library which has the grabbing functionality. Just thought you might be interested:

https://gist.github.com/michalfapso/1755e8a35bb83720c2559ce8ffde5f85

**Comment by julzhk** [comment]
Thank you for your link - might help someone in the future so I've added a link to your gist in the read me. 

One day I might incorporate evdev into the main code (hadn't heard of it before tbh!)

best wishes & thanks again!
